// ─── Enum Literal Types ───────────────────────────────────────────────────────

export type UserRole = 'admin' | 'instructor' | 'student';
export type StudentStatus = 'active' | 'graduated' | 'dropped';
export type VehicleStatus = 'active' | 'in_repair' | 'retired';
export type LessonType = 'theory' | 'practice';
export type LessonStatus = 'scheduled' | 'completed' | 'cancelled';
export type ExamType =
  | 'internal_theory'
  | 'internal_practice'
  | 'state_theory'
  | 'state_practice';
export type ExamStatus = 'scheduled' | 'passed' | 'failed';
export type PaymentType =
  | 'installment'
  | 'full_course'
  | 'extra_hours'
  | 'state_exam_fee';
export type PaymentStatus = 'pending' | 'paid' | 'overdue';
export type ExpenseCategory =
  | 'vehicle_maintenance'
  | 'fuel'
  | 'salaries'
  | 'rent'
  | 'other';

// ─── Database Row Types ───────────────────────────────────────────────────────
// Each interface mirrors the exact column names in Supabase (snake_case).

export interface Profile {
  id: string;           // UUID — same as auth.users.id
  role: UserRole;
  first_name: string;
  last_name: string;
  phone: string | null;
}

export interface Instructor {
  id: string;           // UUID
  profile_id: string;
  license_number: string;
  is_active: boolean;
}

export interface Student {
  id: string;           // UUID
  profile_id: string;
  egn: string;          // Bulgarian 10-digit personal number
  registration_date: string; // ISO date string (DATE col)
  status: StudentStatus;
}

export interface Category {
  id: string;
  name: string;         // e.g. 'B', 'C', 'AM'
}

export interface Vehicle {
  id: string;
  registration_number: string;
  make: string;
  model: string;
  category_id: string;
  technical_inspection_date: string; // ISO date — GTP expiry
  status: VehicleStatus;
}

export interface StudentCategory {
  id: string;
  student_id: string;
  category_id: string;
  instructor_id: string;
  readiness_status: number; // 0–100 percent readiness
}

export interface Lesson {
  id: string;
  student_id: string;
  instructor_id: string;
  vehicle_id: string | null; // null for theory lessons
  type: LessonType;
  start_time: string;   // ISO timestamptz
  end_time: string;     // ISO timestamptz
  location: string | null;
  status: LessonStatus;
  instructor_notes: string | null;
  grade: number | null; // 2–6 (Bulgarian grading scale)
}

export interface Exam {
  id: string;
  student_id: string;
  type: ExamType;
  exam_date: string;    // ISO timestamptz
  status: ExamStatus;
  score: number | null;
}

export interface Payment {
  id: string;
  student_id: string;
  amount: number;       // DECIMAL stored as number in JS
  type: PaymentType;
  status: PaymentStatus;
  due_date: string;     // ISO date
  payment_date: string | null;
  invoice_number: string | null;
}

export interface Expense {
  id: string;
  description: string;
  amount: number;
  expense_date: string; // ISO date
  category: ExpenseCategory;
}

// ─── Insert Types (id is optional — generated by Supabase) ───────────────────

export type ProfileInsert = Omit<Profile, 'id'> & { id?: string };
export type InstructorInsert = Omit<Instructor, 'id'> & { id?: string };
export type StudentInsert = Omit<Student, 'id'> & { id?: string };
export type CategoryInsert = Omit<Category, 'id'> & { id?: string };
export type VehicleInsert = Omit<Vehicle, 'id'> & { id?: string };
export type StudentCategoryInsert = Omit<StudentCategory, 'id'> & { id?: string };
export type LessonInsert = Omit<Lesson, 'id' | 'location'> & { id?: string; location?: string | null };
export type ExamInsert = Omit<Exam, 'id'> & { id?: string };
export type PaymentInsert = Omit<Payment, 'id'> & { id?: string };
export type ExpenseInsert = Omit<Expense, 'id'> & { id?: string };

// ─── Update Types (all fields optional for PATCH operations) ─────────────────

export type ProfileUpdate = Partial<Omit<Profile, 'id'>>;
export type InstructorUpdate = Partial<Omit<Instructor, 'id'>>;
export type StudentUpdate = Partial<Omit<Student, 'id'>>;
export type CategoryUpdate = Partial<Omit<Category, 'id'>>;
export type VehicleUpdate = Partial<Omit<Vehicle, 'id'>>;
export type StudentCategoryUpdate = Partial<Omit<StudentCategory, 'id'>>;
export type LessonUpdate = Partial<Omit<Lesson, 'id'>>;
export type ExamUpdate = Partial<Omit<Exam, 'id'>>;
export type PaymentUpdate = Partial<Omit<Payment, 'id'>>;
export type ExpenseUpdate = Partial<Omit<Expense, 'id'>>;

// ─── Joined / Composite Response Types ───────────────────────────────────────
// Used when Supabase returns related rows via select('*, profiles(*)') etc.

export interface InstructorWithProfile extends Instructor {
  profiles: Profile;
}

export interface StudentWithProfile extends Student {
  profiles: Profile;
}

export interface VehicleWithCategory extends Vehicle {
  categories: Category;
}

export interface StudentCategoryWithRelations extends StudentCategory {
  students: StudentWithProfile;
  categories: Category;
  instructors: InstructorWithProfile;
}

export interface LessonWithRelations extends Lesson {
  students: StudentWithProfile;
  instructors: InstructorWithProfile;
  vehicles: Vehicle | null;
}

export interface ExamWithStudent extends Exam {
  students: StudentWithProfile;
}

export interface PaymentWithStudent extends Payment {
  students: StudentWithProfile;
}

// ─── Auth / Request Types ─────────────────────────────────────────────────────

export interface AuthenticatedUser {
  id: string;
  email: string;
  role: UserRole;
  profile: Profile;
}

// ─── Standardised API Response Envelope ──────────────────────────────────────

export interface ApiResponse<T> {
  data: T | null;
  error: string | null;
  message?: string;
}

export interface PaginatedResponse<T> {
  data: T[];
  total: number;
  page: number;
  limit: number;
  error: string | null;
}

// ─── Dashboard / Aggregation Types ───────────────────────────────────────────

export interface AdminDashboardStats {
  totalStudents: number;
  activeStudents: number;
  totalInstructors: number;
  activeInstructors: number;
  totalVehicles: number;
  monthlyRevenue: number;
  monthlyExpenses: number;
  upcomingExams: number;
}

export interface FinancialSummary {
  totalRevenue: number;
  totalExpenses: number;
  netProfit: number;
  pendingPayments: number;
  overduePayments: number;
}

export interface InstructorScheduleSummary {
  upcomingLessons: number;
  completedThisMonth: number;
  studentsCount: number;
}

export interface StudentProgressSummary {
  completedTheoryHours: number;
  completedPracticeHours: number;
  requiredTheoryHours: number;
  requiredPracticeHours: number;
  examsPassed: number;
  examsFailed: number;
  totalPaid: number;
  totalOwed: number;
}
